---
# Install and configure build tools.

- name: install gcc
  package:
    name: gcc
    state: present
    update_cache: yes

- name: install git
  package:
    name: git
    state: present
    update_cache: yes
