---
# Install and configure apache.

- name: install Apache and mod_wsgi
  apt: name={{ item }}
       state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: start apache and enable at boot
  service: name=apache2
           enabled=yes
           state=started

- name: open up http, https
  lineinfile: dest=/etc/ferm/ferm.conf
              line='proto tcp dport (http https) ACCEPT;'
              insertafter='# Ansible specified rules.'
  notify: run ferm

