---
# Install the python package dependencies.

- name: install pip
  package:
    name: python3-pip
    state: present

- name: install python packages using apt
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-numpy
    - python3-scipy

- name: install python packages using pip
  pip: name={{ item }}
       executable=pip3
  with_items:
    - scikit-learn
    - biopython
    - Flask
    - Flask-Migrate
    - Flask-SQLAlchemy
    - Flask-Script
    - mysql-connector==2.1.4
#    - forgi


