---

# Install the python package dependencies.

- name: install pip
  yum:
    name: python36-pip
    state: present

- name: install setuptools
  yum:
    name: [ python-setuptools, python36-setuptools ]
    state: present

- name: upgrade pip and setuptools
  pip:
    name: [ pip, setuptools ]
    executable: pip3
    extra_args: --upgrade

- name: install python packages
  yum:
    name: [ python36-scipy, python36-numpy ]
    state: present

- name: install python packages using pip
  pip:
    name: [ biopython, Flask, Flask-Migrate, Flask-SQLAlchemy, Flask-Script, Flask-Babel, mysql-connector ]
    executable: pip3
