---
# Install the python package dependencies.

- include_vars: '{{ item }}'
  with_first_found:
    - files:
       - "{{ ansible_distribution }}.yml"

- name: install pip
  package:
    name: "{{ python_pip }}"
    state: present

- name: install python packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_apt_numpy }}"
    - "{{ python_apt_scipy }}"

- name: install python packages using pip
  pip: name={{ item }}
       executable=pip3
  with_items:
#    - scikit-learn
    - biopython
    - Flask
    - Flask-Migrate
    - Flask-SQLAlchemy
    - Flask-Script
    - Flask-Babel
    - mysql-connector==2.1.4
#    - forgi
