---
# Ansible playbook to install and configure a FoldAtlas server.

- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars.yml

  roles:
    - init
    - build_tools
    - ferm
    - selinux
    - python
    - apache.centos
#    - apache.ubuntu
    - mariadb
    - viennaRNA
    - node.js
    - foldatlas
