---
#
# --- Install ViennaRNA from source ---
#

- name: install dependency packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ viennarna_prereqs }}"

- name: download ViennaRNA source
  unarchive:
    src: "{{ viennarna_src_tarball }}"
    dest: "{{ viennarna_dest }}"
    remote_src: yes
    creates: "{{ viennarna_dest }}/{{ viennarna_version }}.tar.gz"

- name: configure for this VM
  shell: ./configure  --without-perl \
                      --without-python \
                      --without-python3 \
                      --without-kinfold \
                      --without-forester \
                      --without-doc \
                      --without-tutorial \
                      --without-check
  args:
      chdir: "{{ viennarna_dest }}/{{ viennarna_version }}"

- name: build and install
  make:
    chdir: "{{ viennarna_dest }}/{{ viennarna_version }}"
    target: install
