---

# Install and configure MariaDB

- name: install MariaDB 
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-common
    - mariadb-server
    - python-mysqldb

- name: start MariaDB daemon and enable at boot
  service:
    name: mysql
    enabled: yes
    state: started

